CREATE OR REPLACE DATABASE tweet_analysis;
USE DATABASE tweet_analysis;

CREATE OR REPLACE SCHEMA raw_data;

CREATE OR REPLACE STORAGE INTEGRATION s3_int_twitter
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<ACCOUNT ID>:role/snowflake_s3_access_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<RAW Tweets Folder>');

DESC INTEGRATION S3_INT_TWITTER;

CREATE OR REPLACE FILE FORMAT TWEET_JSON_FORMAT
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE STAGE TWEET_STAGE
  URL = 's3://<RAW Tweets Folder>'
  STORAGE_INTEGRATION = s3_int_twitter
  FILE_FORMAT = TWEET_JSON_FORMAT;


